export const trLocalSeoKeywords = [
 "bahçe mobilyası",
 "dış mekan mobilyası",
 "balkon mobilyası",
 "bahçe takımı",
 "bahçe koltuk takımı",
 "dış mekan koltuk takımı",
 "balkon koltuk takımı",
 "oturma grubu",
 "bahçe oturma takımı",
 "dış mekan oturma grubu",
 "köşe bahçe takımı",
 "köşe takımı",
 "bahçe köşe koltuk",
 "teras mobilyası",
 "teras oturma grubu",
 "bahçe masası",
 "masa takımı",
 "salıncak",
 "şezlong",
 "bahçe sandalyesi",
 "bahçe mobilyası online",
 "online bahçe mobilyası",
 "bahçe mobilyası Türkiye",
 "Türkiye bahçe mobilyası",
 "Bursa bahçe mobilyası",
 "İnegöl bahçe mobilyası",
 "İnegöl bahçe takımı",
 "İnegöl dış mekan mobilyası",
 "Fablessi Açelya",
 "Açelya oturma grubu",
 "Açelya bahçe mobilyası",
 "Fablessi Aston",
 "Aston oturma grubu",
 "Aston bahçe mobilyası",
 "Fablessi Begonia",
 "Begonia oturma grubu",
 "Begonia bahçe mobilyası",
 "Fablessi Tesla",
 "Tesla oturma grubu",
 "Tesla bahçe mobilyası",
 "Fablessi Velar",
 "Velar oturma grubu",
 "Velar bahçe mobilyası",
 "Fablessi Trend",
 "Trend oturma grubu",
 "Trend bahçe mobilyası",
 "Fablessi",
];

export const trLocalSeoTitle = "Premium Bahçe ve Balkon Mobilyası";

export const trLocalSeoDescription =
 "Fablessi premium bahçe mobilyası: oturma grupları, köşe takımları, balkon ve dış mekan koleksiyonları. Masa setleri, şezlong, salıncak. Türkiye geneline teslimat. Showroom: İnegöl/Bursa.";

export const trProductSeoDescriptionSuffix =
 "Premium bahçe ve balkon mobilyası — Fablessi dış mekan koleksiyonu, Türkiye geneli.";

export const enLocalSeoKeywords = [
 "garden furniture",
 "outdoor furniture",
 "balcony furniture",
 "garden set",
 "garden sofa set",
 "outdoor sofa set",
 "balcony sofa set",
 "seating set",
 "garden seating set",
 "outdoor seating set",
 "corner garden set",
 "corner set",
 "corner garden sofa",
 "terrace furniture",
 "terrace seating set",
 "garden table",
 "table set",
 "garden swing",
 "sun lounger",
 "garden chairs",
 "online garden furniture",
 "buy garden furniture online",
 "garden furniture Turkey",
 "Turkey garden furniture",
 "Bursa garden furniture",
 "Inegol garden furniture",
 "Inegol garden set",
 "Inegol outdoor furniture",
 "Fablessi Azalea",
 "Azalea seating set",
 "Azalea garden furniture",
 "Fablessi Aston",
 "Aston seating set",
 "Aston garden furniture",
 "Fablessi Begonia",
 "Begonia seating set",
 "Begonia garden furniture",
 "Fablessi Tesla",
 "Tesla seating set",
 "Tesla garden furniture",
 "Fablessi Velar",
 "Velar seating set",
 "Velar garden furniture",
 "Fablessi Trend",
 "Trend seating set",
 "Trend garden furniture",
 "Fablessi",
];

export const enLocalSeoTitle = "Premium Garden & Outdoor Furniture";

export const enLocalSeoDescription =
 "Fablessi premium garden furniture — seating sets, corner groups, table sets, swings, sun loungers and balcony furniture. Crafted in Turkey, delivered nationwide.";

export const enProductSeoDescriptionSuffix =
 "Premium garden and outdoor furniture — Fablessi collection, nationwide delivery in Turkey.";
