export const trLocalSeoKeywords = [
 "bahçe mobilyası",
 "dış mekan mobilyası",
 "balkon mobilyası",
 "bahçe takımı",
 "bahçe koltuk takımı",
 "dış mekan koltuk takımı",
 "balkon koltuk takımı",
 "oturma grubu",
 "bahçe oturma takımı",
 "dış mekan oturma grubu",
 "köşe bahçe takımı",
 "köşe takımı",
 "bahçe köşe koltuk",
 "teras mobilyası",
 "teras oturma grubu",
 "bahçe masası",
 "masa takımı",
 "salıncak",
 "şezlong",
 "bahçe sandalyesi",
 "bahçe mobilyası online",
 "online bahçe mobilyası",
 "bahçe mobilyası Türkiye",
 "Türkiye bahçe mobilyası",
 "Bursa bahçe mobilyası",
 "İnegöl bahçe mobilyası",
 "İnegöl bahçe takımı",
 "İnegöl dış mekan mobilyası",
 "İnegöl'de üretilen bahçe ve balkon mobilyaları",
 "İnegöl'de üretilen bahçe mobilyası",
 "İnegöl'de üretilen balkon mobilyası",
 "İnegöl'de üretilen dış mekan mobilyası",
 "İnegöl üretimi bahçe ve balkon mobilyaları",
 "İnegöl üretimi bahçe mobilyası",
 "İnegöl üretimi balkon mobilyası",
 "İnegöl üretimi dış mekan mobilyası",
 "İnegöl'de üretilen premium bahçe mobilyası",
 "İnegöl üretimi premium bahçe mobilyası",
 "İnegöl'de üretilen bahçe koltuk takımı",
 "İnegöl'de üretilen oturma grubu",
 "Gardossi Açelya",
 "Açelya oturma grubu",
 "Açelya bahçe mobilyası",
 "Gardossi Aston",
 "Aston oturma grubu",
 "Aston bahçe mobilyası",
 "Gardossi Begonia",
 "Begonia oturma grubu",
 "Begonia bahçe mobilyası",
 "Gardossi Tesla",
 "Tesla oturma grubu",
 "Tesla bahçe mobilyası",
 "Gardossi Velar",
 "Velar oturma grubu",
 "Velar bahçe mobilyası",
 "Gardossi Trend",
 "Trend oturma grubu",
 "Trend bahçe mobilyası",
 "Trend bahçe sandalyesi",
 "açık hava mobilyası",
 "rattan bahçe mobilyası",
 "alüminyum bahçe mobilyası",
 "dış mekan rattan mobilya",
 "köşe oturma grubu",
 "bahçe salıncağı",
 "kuş yuvası salıncak",
 "bahçe şezlong",
 "dış mekan sandalye",
 "masa sandalye takımı",
 "balkon oturma grubu",
 "teras koltuk takımı",
 "bahçe mobilyası fiyatları",
 "bahçe koltuk takımı fiyatları",
 "premium bahçe mobilyası",
 "İnegöl mobilya",
 "İnegöl mobilya mağazası",
 "İnegöl mobilya fabrikası",
 "Bursa dış mekan mobilyası",
 "Tesla köşe takımı",
 "Velar köşe takımı",
 "Tesla salıncak",
 "Velar salıncak",
 "Velar şezlong",
 "Tesla bahçe masası",
 "Velar bahçe masası",
 "Gardossi Outdoor Living",
 "Gardossi bahçe mobilyası",
 "Gardossi mobilya",
 "Gardossi",
];

export const trLocalSeoTitle = "İnegöl Bahçe & Balkon Mobilyaları";

export const trLocalSeoDescription =
 "İnegöl'de üretilen bahçe ve balkon mobilyalarımızda oturma gruplarından salıncaklara uzanan koleksiyonun tamamını keşfedin.";

export const enLocalSeoKeywords = [
 "garden furniture",
 "outdoor furniture",
 "balcony furniture",
 "garden set",
 "garden sofa set",
 "outdoor sofa set",
 "balcony sofa set",
 "seating set",
 "garden seating set",
 "outdoor seating set",
 "corner garden set",
 "corner set",
 "corner garden sofa",
 "terrace furniture",
 "terrace seating set",
 "garden table",
 "table set",
 "garden swing",
 "sun lounger",
 "garden chairs",
 "online garden furniture",
 "buy garden furniture online",
 "garden furniture Turkey",
 "Turkey garden furniture",
 "Bursa garden furniture",
 "İnegöl garden furniture",
 "İnegöl garden set",
 "İnegöl outdoor furniture",
 "garden and balcony furniture made in İnegöl",
 "garden furniture made in İnegöl",
 "balcony furniture made in İnegöl",
 "outdoor furniture made in İnegöl",
 "premium garden furniture made in İnegöl",
 "garden seating set made in İnegöl",
 "garden sofa set made in İnegöl",
 "İnegöl made garden furniture",
 "furniture made in İnegöl Turkey",
 "Gardossi Azalea",
 "Azalea seating set",
 "Azalea garden furniture",
 "Gardossi Aston",
 "Aston seating set",
 "Aston garden furniture",
 "Gardossi Begonia",
 "Begonia seating set",
 "Begonia garden furniture",
 "Gardossi Tesla",
 "Tesla seating set",
 "Tesla garden furniture",
 "Gardossi Velar",
 "Velar seating set",
 "Velar garden furniture",
 "Gardossi Trend",
 "Trend seating set",
 "Trend garden furniture",
 "Trend garden chair",
 "outdoor living furniture",
 "rattan garden furniture",
 "aluminum outdoor furniture",
 "outdoor rattan furniture",
 "corner seating set",
 "garden swing chair",
 "egg chair swing",
 "garden sun lounger",
 "outdoor chair",
 "table and chair set",
 "balcony seating set",
 "terrace sofa set",
 "garden furniture prices",
 "garden sofa set prices",
 "premium garden furniture",
 "İnegöl furniture",
 "İnegöl furniture store",
 "İnegöl furniture manufacturer",
 "Bursa outdoor furniture",
 "Gardossi Acelya",
 "Acelya seating set",
 "Acelya garden furniture",
 "Tesla corner set",
 "Velar corner set",
 "Tesla garden swing",
 "Velar garden swing",
 "Velar sun lounger",
 "Tesla garden table",
 "Velar garden table",
 "Gardossi Outdoor Living",
 "Gardossi garden furniture",
 "Gardossi furniture",
 "Gardossi",
];

export const enLocalSeoTitle = "İnegöl Garden and Balcony Furniture";

export const enLocalSeoDescription =
 "Discover our full collection of garden and balcony furniture made in İnegöl, from seating sets to swings.";
