export {
 MdAutorenew as Loader2Icon,
 MdCheck as CheckIcon,
 MdCheckCircle as CircleCheckIcon,
 MdChevronLeft as ChevronLeft,
 MdChevronLeft as ChevronLeftIcon,
 MdChevronRight as ChevronRightIcon,
 MdChevronRight as ChevronRight,
 MdClose as X,
 MdClose as XIcon,
 MdCompareArrows as CompareArrows,
 MdCopyright as Copyright,
 MdFolder as Folder,
 MdCollections as Collections,
 MdExplore as Explore,
 MdPrecisionManufacturing as Factory,
 MdTrackChanges as MissionVision,
 MdHelpOutline as HelpOutline,
 MdHome as Home,
 MdViewModule as ViewModule,
 MdWorkOutline as Work,
 MdStore as Store,
 MdEmail as Mail,
 MdFavoriteBorder as Heart,
 MdFavorite as HeartFilled,
 MdHandshake as Handshake,
 MdLocalShipping as Truck,
 MdStraighten as Ruler,
 MdVerifiedUser as ShieldCheck,
 MdError as OctagonXIcon,
 MdInfo as InfoIcon,
 MdKeyboardArrowDown as ChevronDownIcon,
 MdKeyboardArrowUp as ChevronUpIcon,
 MdMenu as Menu,
 MdMoreHoriz as MoreHorizontalIcon,
 MdPhone as Phone,
 MdLocationOn as MapPin,
 MdSearch as Search,
 MdSearch as SearchIcon,
 MdSupportAgent as SupportAgent,
 MdViewSidebar as PanelLeftIcon,
 MdTune as FilterIcon,
 MdWarning as TriangleAlertIcon,
} from "react-icons/md";

export { FaLocationArrow } from "react-icons/fa";
export { FaWhatsapp } from "react-icons/fa";

export {
 LuChevronLeft as HeroChevronLeft,
 LuChevronRight as HeroChevronRight,
 LuX as CloseIcon,
} from "react-icons/lu";

export { IoLanguageSharp } from "react-icons/io5";
